import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TechLoader from "@/components/SplashScreen";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <TechLoader />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  dark`}
      >
        {children}
      </body>
    </html>
  );
}
